[alias]
# Main test alias - runs all essential tests
testall = "test --package oif-service --lib --package oif-storage --package oif-types --package oif-config --package oif-adapters --package oif-api"
