name: Deploy UI

on:
  push:
    branches: [ release-workflows ]
    paths:
      - "demo/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      WORKDIR: demo
      ROLE_FOR_OIDC: "${{ secrets.ROLE_FOR_OIDC }}"
      ROLE_TO_ASSUME: "${{ secrets.ROLE_TO_ASSUME }}"
      VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}
    steps:
      - uses: actions/checkout@actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Use node@22
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 22.14.0
          cache: 'pnpm'

      - name: Install deps
        working-directory: ${{ env.WORKDIR }}
        run: pnpm install

      - name: Build demo
        working-directory: ${{ env.WORKDIR }}
        run: pnpm build

      - name: Detect build output folder
        id: detect
        run: |
          if [ -d "${{ env.WORKDIR }}/dist" ]; then
            echo "out=dist" >> "$GITHUB_OUTPUT"
          else
            echo "No dist/ folder found; double check the pnpm build command" >&2
            exit 1
          fi

      - name: Set up AWS credentials via OIDC and role chaining
        uses: ./.github/actions/oidc
        with:
          role-for-oidc: ${{ env.ROLE_FOR_OIDC }}
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}

      - name: Sync to S3 Bucket
        run: |
          aws s3 sync "${{ env.WORKDIR }}/${{ steps.detect.outputs.out }}/" "s3://${{ secrets.S3_BUCKET }}/" \
            --delete \
            --cache-control "public,max-age=31536000,immutable" \
            --exclude "index.html"
          aws s3 cp "${{ env.WORKDIR }}/${{ steps.detect.outputs.out }}/index.html" "s3://${{ secrets.S3_BUCKET }}/index.html" \
            --cache-control "no-cache,no-store,must-revalidate" \
            --content-type "text/html"

      - name: Invalidate CloudFront Distribution
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${{ secrets.CF_DISTRIBUTION_ID }}" \
            --paths "/*"
